import Head from "next/head";
import Nav from "../components/Nav";
import Image from "next/image";

export default function Home() {
  return (
    // CSS Modules: style specific to a page or component
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Nav />

      <main>
        <h1>Web Design and Development</h1>
        <div>
        <Image
          className="avatar"
          src="/img/photo.jpg"
          alt=""
          width="100"
          height="100"
        />
        </div>

        <p>
        EliWeb is a web development and design company. We provide best services in website development, design, support, domain and hosting and CEO strategies to our customers according to their requirements. We help our customers to introduce their services and products easier and facilitate their sale process to have rise in sale.  
        <br/>We are committed to offer our services at reasonable price and deliver them according to your needs at the agreed time.
        </p>
      </main>
    </div>
  );
}
