import Head from "next/head";
import Nav from "../components/Nav";
import Image from "next/image";
import Footer from "../components/Footer";

export default function About() {
  return (
    <div>
      <Head>
        <title>EliWeb-Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.svg" />
      </Head>

      <Nav />

      <main>
        {/* Using image component has advantages such as image responsiveness and optimization (learn more at: https://nextjs.org/learn/basics/assets-metadata-css/assets) */}

        <h1>Services</h1>

        <ul>
            <li>Design websites </li>
            <li>Develop web applications </li>
            <li>Responsive design </li>
            <li>Design Logos  </li>
            <li>Create animations, assets and contents </li>
            <li>CEO </li>
            <li>Domain and hosting  </li>
            <li>Support </li>
          </ul>
          <br/>
          <Image
          className="image"
          src="/img/price2.jpg"
          alt=""
          width="945"
          height="280"
        />
      </main>
      <Footer/>
    </div>
  );
}
